version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    nodejs: "20"
  commands:
    - npm install antora
    - npx -y antora --fetch --to-dir $READTHEDOCS_OUTPUT/html antora-playbook.yml
